# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossdist2 <- function(x, y) {
    .Call(`_graphmetrics_crossdist2`, x, y)
}

crossdist <- function(x, y) {
    .Call(`_graphmetrics_crossdist`, x, y)
}

edgedist <- function(e, f, maxedist = 1.0, bound = TRUE, edge_weighted = FALSE) {
    .Call(`_graphmetrics_edgedist`, e, f, maxedist, bound, edge_weighted)
}

edgedist1 <- function(e, f, maxedist = 1.0, bound = TRUE) {
    .Call(`_graphmetrics_edgedist1`, e, f, maxedist, bound)
}

compute_pers_values <- function(i, nn, pers_to_obj, obj_to_pers, maxcost, dmat, sigma, tau, prices, maxedist, multe, bound, vfac, efac) {
    .Call(`_graphmetrics_compute_pers_values`, i, nn, pers_to_obj, obj_to_pers, maxcost, dmat, sigma, tau, prices, maxedist, multe, bound, vfac, efac)
}

compute_pers_values2 <- function(i, nn, pers_to_obj, obj_to_pers, maxcost, dmat, sigma, tau, prices, maxedist, multe, bound, vfac, efac) {
    .Call(`_graphmetrics_compute_pers_values2`, i, nn, pers_to_obj, obj_to_pers, maxcost, dmat, sigma, tau, prices, maxedist, multe, bound, vfac, efac)
}

auction_match_Cpp <- function(sigma, tau, dmat, nn, maxcost, compensate, numtype, CE = 1.0, stop_at = 1L, maxiter = 100L, eps = 0.01, verbose = 0L) {
    .Call(`_graphmetrics_auction_match_Cpp`, sigma, tau, dmat, nn, maxcost, compensate, numtype, CE, stop_at, maxiter, eps, verbose)
}

msm_levene_Cpp <- function(dmat, n1, n2, balanced = TRUE, nperm = 999L, alpha = 0.05) {
    .Call(`_graphmetrics_msm_levene_Cpp`, dmat, n1, n2, balanced, nperm, alpha)
}

